# Generated by Django 3.0.3 on 2020-05-25 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Work',
        ),
    ]
