# Generated by Django 3.0.3 on 2020-05-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_auto_20200525_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='work',
            name='done',
        ),
        migrations.AddField(
            model_name='work',
            name='category',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='work',
            name='hsize',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='work',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='work',
            name='media',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='work',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='work',
            name='surface',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='work',
            name='vsize',
            field=models.IntegerField(default=0),
        ),
    ]
