# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-04 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='product',
            new_name='work',
        ),
    ]
