# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-21 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('subject', models.CharField(choices=[('general', 'General'), ('commission', 'Commission'), ('feedback', 'Feedback'), ('other', 'Other')], default='General', max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
