# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-15 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_auto_20200615_1954'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Commissions',
        ),
    ]
