# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-31 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='name',
            field=models.CharField(default='', max_length=254),
        ),
    ]
